CREATE DATABASE dino default CHARACTER SET UTF8;
use dino;
CREATE TABLE usertbl(
    userid VARCHAR(300) PRIMARY KEY NOT NULL,
    userpw VARCHAR(300) NOT NULL,
    userplan VARCHAR(300) NOT NULL,
    username VARCHAR(300) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    business_number VARCHAR(50) NOT NULL,
    userdate DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;
CREATE TABLE apikey(
    userid VARCHAR(300) PRIMARY KEY NOT NULL,
    ssid VARCHAR(300),
    sspw VARCHAR(300),
    atid VARCHAR(300),
    atpw VARCHAR(300),
    cpid VARCHAR(300),
    cpcode VARCHAR(300),
    cpak VARCHAR(300),
    cpsk VARCHAR(300),
    cpday VARCHAR(300),
    elevenapi VARCHAR(300),
    rtapi VARCHAR(300),
    rtday VARCHAR(300),
    wpid VARCHAR(300),
    wppw VARCHAR(300)
) ENGINE=INNODB;
CREATE TABLE taobao(
    productid VARCHAR(300) PRIMARY KEY NOT NULL,
    title VARCHAR(300) NOT NULL,
    price VARCHAR(300) NOT NULL,
    orginalprice VARCHAR(300) NOT NULL
) ENGINE=INNODB;
CREATE TABLE taobaoimg(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    productid VARCHAR(300) NOT NULL,
    img VARCHAR(300) NOT NULL
) ENGINE=INNODB;
CREATE TABLE prop(
    propid VARCHAR(300) PRIMARY KEY NOT NULL,
    productid VARCHAR(300) NOT NULL,
    propname VARCHAR(300) NOT NULL,
    price VARCHAR(300) NOT NULL,
    orginalprice VARCHAR(300) NOT NULL,
    img VARCHAR(300) NOT NULL
) ENGINE=INNODB;
CREATE TABLE descimg(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    productid VARCHAR(300) NOT NULL,
    img VARCHAR(300) NOT NULL
) ENGINE=INNODB;
CREATE TABLE userproduct(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    userid VARCHAR(300) NOT NULL,
    productid VARCHAR(300) NOT NULL
) ENGINE=INNODB;